{% set name = "aiida-dataframe" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida-dataframe-{{ version }}.tar.gz
  sha256: a0f08db2e9fdd4283ec9c5a89e10d3e86ed0fa1464844ed43dfaaa6cff56db65

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core >=3.4,<4
  run:
    - aiida-core >=1.0,<3
    - pandas
    - python >=3.7
    - pytables
    - tabulate

test:
  imports:
    - aiida_dataframe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/aiida-dataframe/
  summary: AiiDA data plugin for pandas DataFrame objects
  dev_url: https://github.com/janssenhenning/aiida-dataframe
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janssenhenning
