{% set name = "aiida-dataframe" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 99b88c23f778c5f568e6cda5bb4ea95f971da7f7f39b80809952eaa6a4143fd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.4,<4
  run:
    - aiida-core >=1.0,<3
    - pandas
    - python >={{ python_min }}
    - pytables
    - tabulate

test:
  imports:
    - aiida_dataframe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/aiida-dataframe/
  summary: AiiDA data plugin for pandas DataFrame objects
  dev_url: https://github.com/janssenhenning/aiida-dataframe
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janssenhenning
